# Predicts

In [1]:
import pandas as pd
import numpy as np
import pickle

In [16]:
data_test = pd.read_csv("../data/processed/df_test.csv")
data_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6       98             58             33      190  34.0   
1            2      112             75             32        0  35.7   
2            2      108             64              0        0  30.8   
3            8      107             80              0        0  24.6   
4            7      136             90              0        0  29.9   

   DiabetesPedigreeFunction  Age  
0                     0.430   43  
1                     0.148   21  
2                     0.158   21  
3                     0.856   34  
4                     0.210   50

Verificamos que no haya nulos

In [17]:
data_test.isnull().mean()

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
dtype: float64

Eliminamos columnas

In [18]:
data_test.drop(['SkinThickness', 'Insulin'], axis=1, inplace=True)

Imputación de datos

In [19]:
with open("../artifacts/feature_eng_configs.pkl","rb") as f:
    feature_eng_configs = pickle.load(f)

feature_eng_configs

{'Glucose_imputed_value': 121,
 'BloodPressure_imputed_value': 67,
 'BMI_imputed_value': 32}

In [20]:
data_test["Glucose"] = data_test["Glucose"].replace(0, feature_eng_configs["Glucose_imputed_value"]).astype(int)
data_test["BloodPressure"] = data_test["BloodPressure"].replace(0, feature_eng_configs["BloodPressure_imputed_value"]).astype(int)
data_test["BMI"] = data_test["BMI"].replace(0, feature_eng_configs["BMI_imputed_value"]).astype(int)

data_test.head(10)

Pregnancies  Glucose  BloodPressure  BMI  DiabetesPedigreeFunction  Age
0            6       98             58   34                     0.430   43
1            2      112             75   35                     0.148   21
2            2      108             64   30                     0.158   21
3            8      107             80   24                     0.856   34
4            7      136             90   29                     0.210   50
5            6      103             72   37                     0.324   55
6            1       71             48   20                     0.323   22
7            0      117             67   33                     0.932   44
8            4      154             72   31                     0.338   37
9            5      147             78   33                     0.218   65

Estandarización con artefacto guardado

In [21]:
with open("../artifacts/mm_scaler.pkl", "rb") as f:
    mm_scaler = pickle.load(f)

mm_scaler

MinMaxScaler()

In [ ]:
X_data_test_std = mm_scaler.transform(data_test)

array([[0.46153846, 0.28346457, 0.15151515, 0.47058824, 0.25465839,
        0.5       ],
       [0.15384615, 0.39370079, 0.40909091, 0.5       , 0.03571429,
        0.        ],
       [0.15384615, 0.36220472, 0.24242424, 0.35294118, 0.04347826,
        0.        ],
       [0.61538462, 0.35433071, 0.48484848, 0.17647059, 0.58540373,
        0.29545455],
       [0.53846154, 0.58267717, 0.63636364, 0.32352941, 0.08385093,
        0.65909091],
       [0.46153846, 0.32283465, 0.36363636, 0.55882353, 0.17236025,
        0.77272727],
       [0.07692308, 0.07086614, 0.        , 0.05882353, 0.17158385,
        0.02272727],
       [0.        , 0.43307087, 0.28787879, 0.44117647, 0.64440994,
        0.52272727],
       [0.30769231, 0.72440945, 0.36363636, 0.38235294, 0.18322981,
        0.36363636],
       [0.38461538, 0.66929134, 0.45454545, 0.44117647, 0.09006211,
        1.        ],
       [0.76923077, 0.38582677, 0.33333333, 0.26470588, 0.0302795 ,
        0.43181818],
       [0.53846154, 0

Cargamos modelos ya entrenados

In [23]:
with open("../models/gb_model.pkl", "rb") as f:
    modelo_gb = pickle.load(f)

modelo_gb

GradientBoostingClassifier(learning_rate=0.05, n_estimators=25, random_state=42)

In [32]:
data_test_predicts_gb = modelo_gb.predict(X_data_test_std)
data_test_predicts_gb

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
with open("../models/knn_model.pkl", "rb") as f:
    modelo_knn = pickle.load(f)

modelo_knn

KNeighborsClassifier()

In [31]:
data_test_predicts_knn = modelo_knn.predict(X_data_test_std)
data_test_predicts_knn

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [25]:
with open("../models/logistic_regression_model.pkl", "rb") as f:
    modelo_lr = pickle.load(f)

modelo_lr

LogisticRegression(random_state=42)

In [30]:
data_test_predicts_lr = modelo_lr.predict(X_data_test_std)
data_test_predicts_lr

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
with open("../models/random_forest_model.pkl", "rb") as f:
    modelo_rf = pickle.load(f)

modelo_rf

RandomForestClassifier(random_state=42)

In [33]:
data_test_predicts_rf = modelo_rf.predict(X_data_test_std)
data_test_predicts_rf

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [27]:
with open("../models/svc_model.pkl", "rb") as f:
    modelo_svc = pickle.load(f)

modelo_svc

SVC(kernel='linear', random_state=42)

In [ ]:
data_test_predicts_svc = modelo_rf.predict(X_data_test_std)
data_test_predicts_svc