# Predicts

In [1]:
import pandas as pd
import numpy as np
import pickle

In [2]:
data_test = pd.read_csv("../data/processed/df_test.csv")
data_test.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6       98             58             33      190  34.0   
1            2      112             75             32        0  35.7   
2            2      108             64              0        0  30.8   
3            8      107             80              0        0  24.6   
4            7      136             90              0        0  29.9   

   DiabetesPedigreeFunction  Age  
0                     0.430   43  
1                     0.148   21  
2                     0.158   21  
3                     0.856   34  
4                     0.210   50

Verificamos que no haya nulos

In [3]:
data_test.isnull().mean()

Pregnancies                 0.0
Glucose                     0.0
BloodPressure               0.0
SkinThickness               0.0
Insulin                     0.0
BMI                         0.0
DiabetesPedigreeFunction    0.0
Age                         0.0
dtype: float64

Eliminamos columnas

In [4]:
data_test.drop(['SkinThickness', 'Insulin'], axis=1, inplace=True)

Imputación de datos

In [5]:
with open("../artifacts/feature_eng_configs.pkl","rb") as f:
    feature_eng_configs = pickle.load(f)

feature_eng_configs

{'Glucose_imputed_value': 121,
 'BloodPressure_imputed_value': 67,
 'BMI_imputed_value': 32}

In [6]:
data_test["Glucose"] = data_test["Glucose"].replace(0, feature_eng_configs["Glucose_imputed_value"]).astype(int)
data_test["BloodPressure"] = data_test["BloodPressure"].replace(0, feature_eng_configs["BloodPressure_imputed_value"]).astype(int)
data_test["BMI"] = data_test["BMI"].replace(0, feature_eng_configs["BMI_imputed_value"]).astype(int)

data_test.head(10)

Pregnancies  Glucose  BloodPressure  BMI  DiabetesPedigreeFunction  Age
0            6       98             58   34                     0.430   43
1            2      112             75   35                     0.148   21
2            2      108             64   30                     0.158   21
3            8      107             80   24                     0.856   34
4            7      136             90   29                     0.210   50
5            6      103             72   37                     0.324   55
6            1       71             48   20                     0.323   22
7            0      117             67   33                     0.932   44
8            4      154             72   31                     0.338   37
9            5      147             78   33                     0.218   65

Estandarización con artefacto guardado

In [7]:
with open("../artifacts/mm_scaler.pkl", "rb") as f:
    mm_scaler = pickle.load(f)

mm_scaler

MinMaxScaler()

In [8]:
X_data_test_std = mm_scaler.transform(data_test)

Cargamos modelos ya entrenados

In [9]:
with open("../models/gb_model.pkl", "rb") as f:
    modelo_gb = pickle.load(f)

modelo_gb

GradientBoostingClassifier(learning_rate=0.05, n_estimators=25, random_state=42)

In [10]:
data_test_predicts_gb = modelo_gb.predict(X_data_test_std)
data_test_predicts_gb

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but GradientBoostingClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [11]:
with open("../models/knn_model.pkl", "rb") as f:
    modelo_knn = pickle.load(f)

modelo_knn

KNeighborsClassifier()

In [12]:
data_test_predicts_knn = modelo_knn.predict(X_data_test_std)
data_test_predicts_knn

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [13]:
with open("../models/logistic_regression_model.pkl", "rb") as f:
    modelo_lr = pickle.load(f)

modelo_lr

LogisticRegression(random_state=42)

In [14]:
data_test_predicts_lr = modelo_lr.predict(X_data_test_std)
data_test_predicts_lr

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

In [15]:
with open("../models/random_forest_model.pkl", "rb") as f:
    modelo_rf = pickle.load(f)

modelo_rf

RandomForestClassifier(random_state=42)

In [16]:
data_test_predicts_rf = modelo_rf.predict(X_data_test_std)
data_test_predicts_rf

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])

In [17]:
with open("../models/svc_model.pkl", "rb") as f:
    modelo_svc = pickle.load(f)

modelo_svc

SVC(kernel='linear', random_state=42)

In [18]:
data_test_predicts_svc = modelo_rf.predict(X_data_test_std)
data_test_predicts_svc

c:\Users\USUARIO\anaconda3\envs\venv-diabetes-model\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])